#!/usr/bin/env bash

set -e 

DEVICE=${1-'/'}

OUTPUT=$(btrfs device stats $DEVICE)
ERRORS=$(echo $OUTPUT | grep -vE ' 0$' || true)

if [ "$ERRORS" == "" ]; then
  echo "BTRFS Checked OK"
  exit 0
else
  echo "BTRFS Errors: $ERRORS"
  exit 2
fi
