#!/bin/bash
#
# Email Host Alert
#
# More compact alert format
#
# Andrew Cutler 2012-04-01
#

CONTACTEMAIL=$ICINGA_CONTACTEMAIL
HOSTSTATE=$ICINGA_HOSTSTATE
HOSTNAME=$ICINGA_HOSTNAME
HOSTALIAS=$ICINGA_HOSTALIAS
HOSTOUTPUT=$ICINGA_HOSTOUTPUT
TIMEDATE="$ICINGA_TIME $ICINGA_DATE"

echo -e "To: ${CONTACTEMAIL}\r
Subject: Alert ${HOSTSTATE:0:4} - ${HOSTNAME}\r
\r
Host State: ${HOSTSTATE}\r
Hostname: ${HOSTNAME}\r
Host Alias: ${HOSTALIAS}\r
Output: ${HOSTOUTPUT}\r
Time: ${TIMEDATE}\r
URL: ${HOSTACTIONURL}" | /usr/sbin/sendmail -i -f icinga@`hostname` ${CONTACTEMAIL}
