#!/bin/bash

# Find our Nagios / Icinga / NRPE plugin wherever it might be
# Andrew Cutler / Adlibre Pty Ltd

PLUGIN=$1
CHECK_ARGS=`shift; echo "$@"`

if [ -f "/etc/nagios/plugins/${PLUGIN}" ]; then
    /etc/nagios/plugins/${PLUGIN} ${CHECK_ARGS}
    exit $?;
elif [ -f "/usr/lib64/nagios/plugins/${PLUGIN}" ]; then
    /usr/lib64/nagios/plugins/${PLUGIN} ${CHECK_ARGS}
    exit $?;
elif [ -f "/usr/lib/nagios/plugins/${PLUGIN}" ]; then
    /usr/lib/nagios/plugins/${PLUGIN} ${CHECK_ARGS}
    exit $?;
elif [ -f "/opt/nagios/libexec/${PLUGIN}" ]; then
    /opt/nagios/libexec/${PLUGIN} ${CHECK_ARGS}
    exit $?;
else
    echo "Plugin ${PLUGIN} not found."
    exit 3 # unknown
fi

